web:
  replicaCount: 2
  autoscaling:
    enabled: true
    minReplicas: 2
  ingress:
    enabled: true
    annotations:
      # share a single ALB with all ingress rules with group
      alb.ingress.kubernetes.io/group.name: onepiece-group-sg-test
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
      # waf, only works for regional waf
      alb.ingress.kubernetes.io/waf-acl-id: e4b45857-5e47-44da-b6d3-209bf1357a49
      # test-vpc-apse1-alb_sg
      alb.ingress.kubernetes.io/security-groups: sg-023fd772faf2aa4a1
      # tls certificates for .com, .co, .sg, .com.au
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-southeast-1:825303761615:certificate/d33d5157-fce4-4f7c-a38a-54a74368e8ff,arn:aws:acm:ap-southeast-1:825303761615:certificate/779b0800-a159-436b-b360-c4a1510bc2ef,arn:aws:acm:ap-southeast-1:825303761615:certificate/86d20706-d9e9-4a2b-b837-3530be7c7743,arn:aws:acm:ap-southeast-1:825303761615:certificate/4363372c-2c48-48fe-ba3d-1cc7e979c01b
      # alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-southeast-1:825303761615:certificate/4f0499e7-704f-4309-a376-d29bb2b23ad8
      alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-2-2017-01
      alb.ingress.kubernetes.io/healthcheck-path: /health
      alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '10'
      alb.ingress.kubernetes.io/load-balancer-attributes: routing.http2.enabled=true,routing.http.drop_invalid_header_fields.enabled=true,waf.fail_open.enabled=true,access_logs.s3.enabled=true,access_logs.s3.bucket=alb-log-waf-onepiece-sg-230,access_logs.s3.prefix=onepiece-group-sg-test
      alb.ingress.kubernetes.io/ssl-redirect: '443'
    hosts:
      - host: www-test.castlery.com
        paths:
          - '/*'
