name: APP Release CI/CD

on:
  # repository_dispatch:
  #   types: [release-pos]
  release:
    types: [published]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  contents: write
  pull-requests: write

jobs:
  APP-CI-CD:
    ## only run on source tags
    if: contains(github.ref, 'source')
    # docs: https://docs.github.com/zh/actions/using-jobs/using-a-matrix-for-your-jobs
    strategy:
      matrix:
        include:
          - country: sg
            s3region: ap-southeast-1
            bucket: knight-sg-prod
          - country: au
            s3region: ap-southeast-2
            bucket: knight-au-prod
          - country: us
            s3region: ap-southeast-1
            bucket: knight-us-prod
          - country: ca
            s3region: ca-central-1
            bucket: knight-ca-prod
          - country: uk
            s3region: eu-west-2
            bucket: knight-uk-prod
      fail-fast: false
    uses: ./.github/workflows/CICD-COMPOSE.yaml
    with:
      base-branch: master
      last-successful-event: release
      env: prod
      country: ${{ matrix.country }}
      upload-assets: true
      include-nginx: false
      s3region: ${{ matrix.s3region }}
      bucket: ${{ matrix.bucket }}
    secrets: inherit

  RESET_BRANCH:
    if: contains(github.ref, 'source')
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Reset branch
        run: |
          branches=("uat-au" "uat-sg" "uat-us" "uat-ca" "uat-uk" "test-au" "test-sg" "test-us" "test-uk" "fortress-beta")
          for branch in "${branches[@]}"; do
            git checkout $branch
            git reset --hard ${{ github.ref }}
            git push --force
          done
