export enum SupportedPaymentMethods {
  CREDIT_CARD = 'CREDIT_CARD',
  EXPRESS_PAYMENT = 'EXPRESS_PAYMENT',
  PAYPAL = 'PAYPAL',
  AFTER_PAY = 'AFTER_PAY',
  GRAB_PAY = 'GRAB_PAY',
  ZIP_PAY = 'ZIP_PAY',
  INSTALMENT_2C2P = 'INSTALMENT_2C2P',
  AFFIRM = 'AFFIRM',
}
