const rawData = {
  choices: [
    {
      id: 962492,
      name: 'Cart Recommendations 2',
      type: 'RECS_DECISION',
      variations: [
        {
          id: 28827258,
          payload: {
            data: {
              custom: {
                title: 'Test Old Template 2',
              },
              slots: [
                {
                  sku: 'AS-000194-TL4002-SV',
                  productData: {
                    group_id: 'TAS-000192',
                    categories: ['Sofas', 'Sectional Sofas'],
                    keywords: ['Sofas', 'Sectional Sofas', 'Adams Collection'],
                    in_stock: true,
                    publish_time: '2025-02-19T03:41:05',
                    name: 'Adams Chaise Sectional Sofa Right Facing, Pearl Beige (Silver Leg)',
                    url: 'https://www-test.castlery.com/sg/products/adams-chaise-sectional-sofa?leg_color=silver&material=pearl_beige&orientation=right_facing',
                    image_url:
                      'https://res.cloudinary.com/castlery/image/private/b_rgb:FFFFFF,c_fit,f_auto,q_auto,w_750/v1619340871/crusader/variants/T50440970-TL4002-SV/Adams-Right-Chaise-Setcional-Sofa-Pearl-Beige-Silver-Front.jpg',
                    price: 1899,
                    color: 'Beige',
                    dy_display_price: '1899.0',
                    featured: '',
                    west_quick_ship: '',
                    is_new: 'false',
                    west_good_leadtime: '',
                    collection: 'Adams Collection',
                    left_in_stock: '9999',
                    east_quick_ship: '',
                    is_sale: 'false',
                    sale_price: '',
                    product_tag:
                      'modern_farmhouse,removable_covers,coastal,modern_contemporary,holiday,icu_list,all_sofa,style_moderncontemporary,minimalist_furniture,all product excluding customisation,all products,customisable,bestsellers,storewide_sale',
                    is_clearance: 'false',
                    spu_name: 'Adams Chaise Sectional Sofa. Adams Collection. Sectional Sofas, Sofas, Living Room Furniture',
                    east_good_leadtime: '',
                    material: 'Fabric|Metal',
                    badge_url: '',
                    include_swatch: 'true',
                    deliver: '3 - 5 weeks',
                    delivery_before_x: 'false',
                    lifestyle_image:
                      'https://res.cloudinary.com/castlery/image/private/c_fit,f_auto,q_auto,w_1200/v1654739739/crusader/variants/T50440970-TL4002-SV/Adams-Chaise-Sectional-Sofa-Right-Facing-Pearl-Beige-Silver-Leg-Shared1__1_-1654739737.jpg',
                    additional_image_link:
                      '["https://res.cloudinary.com/castlery/image/private/c_fit,f_auto,q_auto,w_1200/v1700813505/crusader/variants/AS-000189-TL4002-SV/Adams-Chaise-Sectional-Sofa-Right-Facing-Seat-Pearl-Beige-Set_2-1700813503.jpg", "https://res.cloudinary.com/castlery/image/private/c_fit,f_auto,q_auto,w_1200/v1621859286/crusader/variants/T50440970-TL4002-SV/Adams-Chaise-Sectional-Sofa-Right-Facing-Seat-Pearl-Beige-Set_4.jpg", "https://res.cloudinary.com/castlery/image/private/c_fit,f_auto,q_auto,w_1200/v1659601268/crusader/variants/T50440970-TL4002-SV/Adams-Chaise-Sectional-Sofa-Right-Facing-Seat-Pearl-Beige-Set_2-1659601266.jpg", "https://res.cloudinary.com/castlery/image/private/c_fit,f_auto,q_auto,w_1200/v1621859279/crusader/variants/T50440970-TL4002-SV/Adams-2-Seater-Sofa-Seat-Pearl-Beige-D2.jpg", "https://res.cloudinary.com/castlery/image/private/c_fit,f_auto,q_auto,w_1200/v1621859282/crusader/variants/T50440970-TL4002-SV/Adams-Chaise-Sectional-Sofa-Right-Facing-Seat-Pearl-Beige-D4.jpg", "https://res.cloudinary.com/castlery/image/private/c_fit,f_auto,q_auto,w_1200/v1621859284/crusader/variants/T50440970-TL4002-SV/Adams-Chaise-Sectional-Sofa-Right-Facing-Seat-Pearl-Beige-D7.jpg"]',
                    shortest_lead_time: '15',
                    icu: '',
                    southeast_quick_ship: '',
                    northwest_quick_ship: '',
                    southeast_good_leadtime: '',
                    northwest_good_leadtime: '',
                    regional_icu: '0',
                    regional_stock: '1',
                    ToShow:
                      '50440775-LP4001|54000104-LE4020|50440514-TW4004|50440807-TD4002|50440788-TD4001|54000041-LP4001|54000061-IN4002|54000018-BW4002|41360026|50220004|52460040|50850043|40550126|50220002|40550213|50520016|50520017-BO|52460048|52460085|40550220|41360025|50220006|50850009|50220001|40550210|50520015|50850025|41230001|50850016|50850023|41960018|54000019-BW4001|54000019-BW4002',
                    badges: 'Customisable,Storewide Sale,Bestseller',
                    is_blog: '',
                    option_value_material: 'Pearl Beige',
                    blog_description: '',
                    product_breadcrumbs:
                      '[{"name":"Menu","permalink":"menu","level":0},{"name":"Sofas","permalink":"sofas","level":1},{"name":"Sectional Sofas","permalink":"sofas/sectional-sofas","level":2}]',
                  },
                  slotId:
                    'mIOkdHlwZaRDQVJUqGxvY2F0aW9u2SVodHRwczovL3d3dy10ZXN0LmNhc3RsZXJ5LmNvbS9zZy9jYXJ0pGRhdGGRqDU0MDAwMTI5zVPuzgAF4UfCALNBUy0wMDAxOTQtVEw0MDAyLVNWAQA=*nLQtNTkwNTM4NjE5MzA2ODgwMDAyOc4AGsEAqDEzNDAyOTI5AZCRzgG33nqlODIyNDjA2SA0YjExZTY3YzU0YjVjYWE3NDg4YWE5YTE3OWZlNTExM7MxMzQxNDAwODkxNjE0MjczMDcywMA=',
                },
                {
                  sku: '40550100',
                  productData: {
                    group_id: 'T40550108',
                    categories: ['Beds', 'Beds & Bed Frames'],
                    keywords: ['Beds', 'Beds & Bed Frames', 'Seb Collection'],
                    in_stock: true,
                    publish_time: '2025-02-19T03:41:05',
                    name: 'Seb Queen Size Bed',
                    url: 'https://www-test.castlery.com/sg/products/seb-bed?bed_frame_size=queen&material=dark_graphite',
                    image_url:
                      'https://res.cloudinary.com/castlery/image/private/b_rgb:FFFFFF,c_fit,f_auto,q_auto,w_750/v1623988273/crusader/variants/40550100/Seb-Queen-Bed-Front.jpg',
                    price: 999,
                    color: 'Brown',
                    dy_display_price: '999.0',
                    featured: '',
                    west_quick_ship: '',
                    is_new: 'false',
                    west_good_leadtime: '',
                    collection: 'Seb Collection',
                    left_in_stock: '9999',
                    east_quick_ship: '',
                    is_sale: 'false',
                    sale_price: '',
                    product_tag:
                      'woodenbedframes,coastal,web_ar,holiday,icu_list,top_bestsellers,style_midcenturymodern,all_bed,all product excluding customisation,all products,bestsellers,storewide_sale',
                    is_clearance: 'false',
                    spu_name: 'Seb Bed',
                    east_good_leadtime: '',
                    material: 'Wood|Fabric',
                    badge_url: '',
                    include_swatch: 'true',
                    deliver: '3 - 5 weeks',
                    delivery_before_x: 'false',
                    lifestyle_image:
                      'https://res.cloudinary.com/castlery/image/private/c_fit,f_auto,q_auto,w_1200/v1625420549/crusader/variants/40550100/Seb-Queen-Size-Bed-Lifestyle-Crop.jpg',
                    additional_image_link:
                      '["https://res.cloudinary.com/castlery/image/private/c_fit,f_auto,q_auto,w_1200/v1625420549/crusader/variants/40550100/Seb-Bed-Set3.jpg", "https://res.cloudinary.com/castlery/image/private/c_fit,f_auto,q_auto,w_1200/v1636342524/crusader/variants/40550100/Seb-Bed-Set2.jpg", "https://res.cloudinary.com/castlery/image/private/c_fit,f_auto,q_auto,w_1200/v1632387268/crusader/variants/40550100/Seb-Bed-Fabric-Det1.jpg", "https://res.cloudinary.com/castlery/image/private/c_fit,f_auto,q_auto,w_1200/v1625420552/crusader/variants/40550100/Seb-Bed-D3.jpg", "https://res.cloudinary.com/castlery/image/private/c_fit,f_auto,q_auto,w_1200/v1632387586/crusader/variants/40550100/Seb-Bed-Fabric-Det4.jpg", "https://res.cloudinary.com/castlery/image/private/c_fit,f_auto,q_auto,w_1200/v1625420552/crusader/variants/40550100/Seb-Bed-D4.jpg", "https://res.cloudinary.com/castlery/image/private/c_fit,f_auto,q_auto,w_1200/v1625420553/crusader/variants/40550100/Seb-Bed-D5.jpg", "https://res.cloudinary.com/castlery/image/private/c_fit,f_auto,q_auto,w_1200/v1631772446/crusader/variants/40550100/Seb-Texture.jpg"]',
                    shortest_lead_time: '15',
                    icu: 'All HS',
                    southeast_quick_ship: '',
                    northwest_quick_ship: '',
                    southeast_good_leadtime: '',
                    northwest_good_leadtime: '',
                    regional_icu: '1',
                    regional_stock: '1',
                    ToShow:
                      '40550198|52460042|40550214|41360028|52460052|54000148|54000005|51160001|51160010|51160009|51160012|51160011',
                    badges: 'Storewide Sale,Bestseller',
                    is_blog: '',
                    option_value_material: 'Dark Graphite',
                    blog_description: '',
                    product_breadcrumbs:
                      '[{"name":"Menu","permalink":"menu","level":0},{"name":"Beds","permalink":"beds","level":1},{"name":"Beds & Bed Frames","permalink":"beds/bedframes","level":2}]',
                  },
                  slotId:
                    'mIOkdHlwZaRDQVJUqGxvY2F0aW9u2SVodHRwczovL3d3dy10ZXN0LmNhc3RsZXJ5LmNvbS9zZy9jYXJ0pGRhdGGRqDU0MDAwMTI5zVPuzgAF4UfCAag0MDU1MDEwMAEB*nLQtNTkwNTM4NjE5MzA2ODgwMDAyOc4AGsEAqDEzNDAyOTI5AZCRzgG33nqlODIyNDjA2SA0YjExZTY3YzU0YjVjYWE3NDg4YWE5YTE3OWZlNTExM7MxMzQxNDAwODkxNjE0MjczMDcywMA=',
                },
                {
                  sku: 'PB-001150',
                  productData: {
                    group_id: 'TPB-001150',
                    categories: ['Chairs', 'Dining Room Sets'],
                    keywords: [
                      'Chairs',
                      'Dining Room Sets',
                      'Tables',
                      'Furniture Sets',
                      'Dining Room Furniture Sets',
                      'Casa Collection',
                    ],
                    in_stock: true,
                    publish_time: '2025-02-19T03:41:05',
                    name: 'Casa Dining Table 180cm with Dining Bench 180cm Set',
                    url: 'https://www-test.castlery.com/sg/products/casa-dining-table-with-dining-bench-set?bench=180_bench&table_length=table_180cm',
                    image_url:
                      'https://res.cloudinary.com/castlery/image/private/b_rgb:FFFFFF,c_fit,f_auto,q_auto,w_750/v1692849924/crusader/variants/PB-001150/Casa-180cm-Dining-Table-With-180cm-Bench-1692849922.jpg',
                    price: 1568,
                    color: 'White',
                    dy_display_price: '1568.0',
                    featured: 'Sale',
                    west_quick_ship: '',
                    is_new: 'false',
                    west_good_leadtime: '',
                    collection: 'Casa Collection',
                    left_in_stock: '9999',
                    east_quick_ship: '',
                    is_sale: 'true',
                    sale_price: '1489.0',
                    product_tag:
                      'furniture_sets,s3_event_tag,style_modernfarmhouse,all product excluding customisation,all products,bestsellers,storewide_sale',
                    is_clearance: 'false',
                    spu_name: 'Casa Dining Table with Bench Set',
                    east_good_leadtime: '',
                    material: 'Wood',
                    badge_url: '',
                    include_swatch: 'false',
                    deliver: '3 - 5 weeks',
                    delivery_before_x: 'false',
                    lifestyle_image:
                      'https://res.cloudinary.com/castlery/image/private/c_fit,f_auto,q_auto,w_1200/v1692431221/crusader/variants/PB-001153/Casa-Rectangular-Dining-Table-Square-Set_2-1692431219.jpg',
                    additional_image_link:
                      '["https://res.cloudinary.com/castlery/image/private/c_fit,f_auto,q_auto,w_1200/v1692431222/crusader/variants/PB-001153/Casa-Rectangular-Dining-Table-Square-Set_1-1692431219.jpg", "https://res.cloudinary.com/castlery/image/private/c_fit,f_auto,q_auto,w_1200/v1692431536/crusader/variants/PB-001153/Casa-Dining-Table-Square-Det_2-1692431534.jpg", "https://res.cloudinary.com/castlery/image/private/c_fit,f_auto,q_auto,w_1200/v1692431615/crusader/variants/PB-001153/Casa-Dining-Table-Square-Det_1-1692431612.jpg"]',
                    shortest_lead_time: '15',
                    icu: '',
                    southeast_quick_ship: '',
                    northwest_quick_ship: '',
                    southeast_good_leadtime: '',
                    northwest_good_leadtime: '',
                    regional_icu: '0',
                    regional_stock: '1',
                    ToShow: '',
                    badges: 'Set Sale,Sale,Storewide Sale,Bestseller',
                    is_blog: '',
                    option_value_material: '',
                    blog_description: '',
                    product_breadcrumbs:
                      '[{"name":"Menu","permalink":"menu","level":0},{"name":"Chairs","permalink":"chairs","level":1},{"name":"Dining Room Sets","permalink":"chairs/dining-room-bundles","level":2}]',
                  },
                  slotId:
                    'mIOkdHlwZaRDQVJUqGxvY2F0aW9u2SVodHRwczovL3d3dy10ZXN0LmNhc3RsZXJ5LmNvbS9zZy9jYXJ0pGRhdGGRqDU0MDAwMTI5zVPuzgAF4UfCAqlQQi0wMDExNTABAg==*nLQtNTkwNTM4NjE5MzA2ODgwMDAyOc4AGsEAqDEzNDAyOTI5AZCRzgG33nqlODIyNDjA2SA0YjExZTY3YzU0YjVjYWE3NDg4YWE5YTE3OWZlNTExM7MxMzQxNDAwODkxNjE0MjczMDcywMA=',
                },
                {
                  sku: '52460078',
                  productData: {
                    group_id: 'T52460077',
                    categories: ['Beds', 'Beds & Bed Frames'],
                    keywords: ['Beds', 'Beds & Bed Frames', 'Joseph Collection'],
                    in_stock: true,
                    publish_time: '2025-02-19T03:41:05',
                    name: 'Joseph King Size Bed, Walnut',
                    url: 'https://www-test.castlery.com/sg/products/joseph-bed-walnut?bed_frame_size=king',
                    image_url:
                      'https://res.cloudinary.com/castlery/image/private/b_rgb:FFFFFF,c_fit,f_auto,q_auto,w_750/v1624516255/crusader/variants/52460078/Joseph-King-Size-Bed-Walnut-Front-3-SG.jpg',
                    price: 1299,
                    color: 'Brown',
                    dy_display_price: '1299.0',
                    featured: '',
                    west_quick_ship: '',
                    is_new: 'false',
                    west_good_leadtime: '',
                    collection: 'Joseph Collection',
                    left_in_stock: '9999',
                    east_quick_ship: '',
                    is_sale: 'false',
                    sale_price: '',
                    product_tag:
                      'bestseller_sale,coastal,top_bestsellers,all_bed,all product excluding customisation,all products,bestsellers,storewide_sale',
                    is_clearance: 'false',
                    spu_name: 'Joseph Bed, Walnut',
                    east_good_leadtime: '',
                    material: 'Wood',
                    badge_url: '',
                    include_swatch: 'false',
                    deliver: '3 - 5 weeks',
                    delivery_before_x: 'false',
                    lifestyle_image:
                      'https://res.cloudinary.com/castlery/image/private/c_fit,f_auto,q_auto,w_1200/v1627370658/crusader/variants/52460078/Joseph-Bed-Walnut-Lifestyle-Crop.jpg',
                    additional_image_link:
                      '["https://res.cloudinary.com/castlery/image/private/c_fit,f_auto,q_auto,w_1200/v1627370390/crusader/variants/52460078/Joseph-Bed-Walnut-Set_4.jpg", "https://res.cloudinary.com/castlery/image/private/c_fit,f_auto,q_auto,w_1200/v1627370389/crusader/variants/52460078/Joseph-Bed-Walnut-Set_5.jpg", "https://res.cloudinary.com/castlery/image/private/c_fit,f_auto,q_auto,w_1200/v1627370390/crusader/variants/52460078/Joseph-Bed-Walnut-Set_3.jpg", "https://res.cloudinary.com/castlery/image/private/c_fit,f_auto,q_auto,w_1200/v1668395117/crusader/variants/52460080/Joseph-Bed-Walnut-Det_Crop6-1668395115.jpg"]',
                    shortest_lead_time: '15',
                    icu: 'All HS',
                    southeast_quick_ship: '',
                    northwest_quick_ship: '',
                    southeast_good_leadtime: '',
                    northwest_good_leadtime: '',
                    regional_icu: '1',
                    regional_stock: '1',
                    ToShow:
                      '40550198|52460042|40550214|41360028|52460052|54000148|54000005|51160001|51160010|51160009|51160012|51160011',
                    badges: 'Storewide Sale,Bestseller',
                    is_blog: '',
                    option_value_material: '',
                    blog_description: '',
                    product_breadcrumbs:
                      '[{"name":"Menu","permalink":"menu","level":0},{"name":"Beds","permalink":"beds","level":1},{"name":"Beds & Bed Frames","permalink":"beds/bedframes","level":2}]',
                  },
                  slotId:
                    'mIOkdHlwZaRDQVJUqGxvY2F0aW9u2SVodHRwczovL3d3dy10ZXN0LmNhc3RsZXJ5LmNvbS9zZy9jYXJ0pGRhdGGRqDU0MDAwMTI5zVPuzgAF4UfCA6g1MjQ2MDA3OAED*nLQtNTkwNTM4NjE5MzA2ODgwMDAyOc4AGsEAqDEzNDAyOTI5AZCRzgG33nqlODIyNDjA2SA0YjExZTY3YzU0YjVjYWE3NDg4YWE5YTE3OWZlNTExM7MxMzQxNDAwODkxNjE0MjczMDcywMA=',
                },
                {
                  sku: '40550244',
                  productData: {
                    group_id: 'T40550244',
                    categories: ['Tables', 'Dining Tables'],
                    keywords: ['Tables', 'Dining Tables', 'Harper Collection'],
                    in_stock: true,
                    publish_time: '2025-02-19T03:41:05',
                    name: 'Harper Dining Table 180cm, Chestnut',
                    url: 'https://www-test.castlery.com/sg/products/harper-dining-table?colour_option=chestnut_oak&length=1_8m',
                    image_url:
                      'https://res.cloudinary.com/castlery/image/private/b_rgb:FFFFFF,c_fit,f_auto,q_auto,w_750/v1724838425/crusader/variants/40550244/Harper-Dining-Table-180cm-Chestnut-Front-1724838423.jpg',
                    price: 1499,
                    color: 'Brown',
                    dy_display_price: '1499.0',
                    featured: 'New Arrival',
                    west_quick_ship: '',
                    is_new: 'true',
                    west_good_leadtime: '',
                    collection: 'Harper Collection',
                    left_in_stock: '9999',
                    east_quick_ship: '',
                    is_sale: 'false',
                    sale_price: '',
                    product_tag: 'new,all product excluding customisation,all products,storewide_sale',
                    is_clearance: 'false',
                    spu_name: 'Harper Dining Table',
                    east_good_leadtime: '',
                    material: 'Wood',
                    badge_url: '',
                    include_swatch: 'false',
                    deliver: '3 - 5 weeks',
                    delivery_before_x: 'false',
                    lifestyle_image:
                      'https://res.cloudinary.com/castlery/image/private/c_fit,f_auto,q_auto,w_1200/v1725265209/crusader/variants/40550244/Harper-Dining-Table-180cm-Chestnut-Square-Set_1_1-1725265206.jpg',
                    additional_image_link:
                      '["https://res.cloudinary.com/castlery/image/private/c_fit,f_auto,q_auto,w_1200/v1725265209/crusader/variants/40550244/Harper-Dining-Table-180cm-Chestnut-Square-Set_2-1725265206.jpg", "https://res.cloudinary.com/castlery/image/private/c_fit,f_auto,q_auto,w_1200/v1725265209/crusader/variants/40550244/Harper-Dining-Table-180cm-Chestnut-Campaign-Square-Det_1-1725265207.jpg", "https://res.cloudinary.com/castlery/image/private/c_fit,f_auto,q_auto,w_1200/v1725265209/crusader/variants/40550244/Harper-Dining-Table-180cm-Chestnut-Campaign-Square-Det_3-1725265206.jpg", "https://res.cloudinary.com/castlery/image/private/c_fit,f_auto,q_auto,w_1200/v1725850509/crusader/variants/40550244/Harper-Sideboard-Chestnut-Square-Det_9-1725850506.jpg", "https://res.cloudinary.com/castlery/image/private/c_fit,f_auto,q_auto,w_1200/v1726200997/crusader/variants/40550244/Harper-Curved-TV-Console-Det_4-1726200995.jpg"]',
                    shortest_lead_time: '15',
                    icu: '',
                    southeast_quick_ship: '',
                    northwest_quick_ship: '',
                    southeast_good_leadtime: '',
                    northwest_good_leadtime: '',
                    regional_icu: '0',
                    regional_stock: '1',
                    ToShow: '',
                    badges: 'New,Storewide Sale',
                    is_blog: '',
                    option_value_material: '',
                    blog_description: '',
                    product_breadcrumbs:
                      '[{"name":"Menu","permalink":"menu","level":0},{"name":"Tables","permalink":"tables","level":1},{"name":"Dining Tables","permalink":"tables/dining-tables","level":2}]',
                  },
                  slotId:
                    'mIOkdHlwZaRDQVJUqGxvY2F0aW9u2SVodHRwczovL3d3dy10ZXN0LmNhc3RsZXJ5LmNvbS9zZy9jYXJ0pGRhdGGRqDU0MDAwMTI5zVPuzgAF4UfCBKg0MDU1MDI0NAEE*nLQtNTkwNTM4NjE5MzA2ODgwMDAyOc4AGsEAqDEzNDAyOTI5AZCRzgG33nqlODIyNDjA2SA0YjExZTY3YzU0YjVjYWE3NDg4YWE5YTE3OWZlNTExM7MxMzQxNDAwODkxNjE0MjczMDcywMA=',
                },
              ],
            },
            type: 'RECS',
          },
        },
      ],
      groups: ['DY API Campaigns', 'Cart Recommendations'],
      decisionId:
        'nLQtNTkwNTM4NjE5MzA2ODgwMDAyOc4AGsEAqDEzNDAyOTI5AZCRzgG33nqlODIyNDjA2SA0YjExZTY3YzU0YjVjYWE3NDg4YWE5YTE3OWZlNTExM7MxMzQxNDAwODkxNjE0MjczMDcywMA=',
    },
  ],
  cookies: [
    {
      name: '_dyid_server',
      value: '-6021312463848824782',
      maxAge: '31556926',
    },
    {
      name: '_dyjsession',
      value: 'vviwfzlent3m4tmed5oyqls78lla0xgb',
      maxAge: '1800',
    },
  ],
};

export const recData = rawData.choices[0].variations[0].payload.data;
