name: CI/CD for prod-sg
on:
  push:
    tags:
      - '[0-9]*.[0-9]*.[0-9]*'
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/build.yaml
    with:
      APP_ENV: sg-prod
    secrets: inherit

  cd:
    needs: ci
    uses: ./.github/workflows/deploy.yaml
    with:
      app_env: sg-prod
      app_country: sg
      env: prod
      image_tag: ${{ needs.ci.outputs.IMAGE_TAG }}
      s3region: ap-southeast-1
      bucket: knight-sg-prod
      auto_merge: true
    secrets: inherit
