name: CI/CD for test-sg
on:
  push:
    branches:
      - test-sg
  release:
    types: [published]
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/build.yaml
    with:
      APP_ENV: sg-test
    secrets: inherit

  cd:
    needs: ci
    uses: ./.github/workflows/deploy.yaml
    with:
      app_env: sg-test
      app_country: sg
      env: test
      image_tag: ${{ needs.ci.outputs.IMAGE_TAG }}
      s3region: ap-southeast-1
      bucket: knight-sg-stag
      auto_merge: true
    secrets: inherit
