name: CI/CD for uat-uk
on:
  push:
    branches:
      - uat-uk
  release:
    types: [published]
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/build.yaml
    with:
      APP_ENV: uk-uat
    secrets: inherit

  cd:
    needs: ci
    uses: ./.github/workflows/deploy.yaml
    with:
      app_env: uk-uat
      app_country: uk
      env: uat
      image_tag: ${{ needs.ci.outputs.IMAGE_TAG }}
      s3region: eu-west-2
      bucket: knight-uk-uat
      auto_merge: true
    secrets: inherit
