name: CI/CD for uat-ca
on:
  push:
    branches:
      - uat-ca
  release:
    types: [published]
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/build.yaml
    with:
      APP_ENV: ca-uat
    secrets: inherit

  cd:
    needs: ci
    uses: ./.github/workflows/deploy.yaml
    with:
      app_env: ca-uat
      app_country: ca
      env: uat
      image_tag: ${{ needs.ci.outputs.IMAGE_TAG }}
      s3region: ca-central-1
      bucket: knight-ca-uat
      auto_merge: true
    secrets: inherit
