import React from 'react';
import type { Meta, StoryObj } from '@storybook/react';
import { AddressList } from './pos-address-list';
import { PosAddAddress } from '../pos-add-address/pos-add-address-adapter';

const meta: Meta<typeof AddressList> = {
  component: AddressList,
  title: 'module/checkout/PosAddressList',
  parameters: {
    design: {
      type: 'figma',
      url: '',
    },
    // https://github.com/vercel/next.js/discussions/50068
    // nextjs: {
    //   appDirectory: true,
    // },
  },
};
export default meta;
type Story = StoryObj<typeof AddressList>;

export const Primary: Story = {
  args: {
    defaultActiveAddressId: 371307,
    addressList: [
      {
        id: 371307,
        firstname: 'Abby',
        lastname: 'Wang',
        address1: '528 Felosa Drive',
        phone: '+1 (653) 333-3333',
        zipcode: '90036',
        address2: '',
        city: 'city',
        company: '',
        street: '528 Felosa Drive',
        is_manual: true,
        is_temporary: false,
        building_type: null,
        state_name: 'CA',
        google_place_id: 'ChIJIx09IErPwoARjgZb8t9y6gc',
        is_valid: true,
        is_shippable: true,
        country: 'United States',
      },
      {
        id: 371040,
        firstname: 'Abby',
        lastname: 'Wang',
        address1: 'A770 N Interstate Highway 35 Canyon Lake, TX',
        phone: '+1 (653) 333-3333',
        zipcode: '78130',
        city: 'city',
        street: 'A770 N Interstate Highway 35 Canyon Lake, TX',
        is_manual: true,
        is_temporary: false,
        building_type: null,
        state_name: 'CA',
        google_place_id: 'ChIJIx09IErPwoARjgZb8t9y6gc',
        is_valid: true,
        is_shippable: false,
        country: 'United States',
      },
      {
        id: 371041,
        firstname: 'Abby',
        lastname: 'Wang',
        address1: 'A770 N Interstate Highway 35 Canyon Lake, TX',
        phone: '+1 (653) 333-3333',
        zipcode: '78130',
        city: 'city',
        street: 'A770 N Interstate Highway 35 Canyon Lake, TX',
        is_manual: true,
        is_temporary: false,
        building_type: null,
        state_name: 'MD',
        google_place_id: 'ChIJ4669jAzFyYkRmRwRvb1HYto',
        is_valid: true,
        is_shippable: false,
        country: 'United States',
      },
      {
        id: 371042,
        firstname: 'Abby',
        lastname: 'Wang',
        address1: '7700 Bull Run Drive',
        phone: '+1 (653) 333-3333',
        zipcode: '20121',
        city: 'Centreville',
        street: '7700 Bull Run Drive',
        is_manual: true,
        is_temporary: false,
        building_type: null,
        state_name: 'VA',
        google_place_id: 'ChIJC5UMJ7hctokRB3m5Q6TwlZE',
        is_valid: true,
        is_shippable: true,
        country: 'United States',
      },
      {
        id: 371300,
        firstname: 'Castlery 22',
        lastname: 'Wang',
        address1: '21000 Education Court',
        phone: '+1 (651) 234-5678',
        zipcode: '20148',
        city: 'Ashburn',
        street: 'Education Court',
        street_number: '21000',
        is_manual: true,
        is_temporary: false,
        building_type: null,
        state_name: 'VA',
        google_place_id: 'ChIJtYG7YVg-tokR8t8Egby0pIA',
        is_valid: true,
        is_shippable: true,
        country: 'United States',
      },
      {
        id: 371301,
        firstname: 'Castlery 22',
        lastname: 'Wang',
        address1: '28077 Chagrin Boulevard',
        phone: '+1 (651) 234-5678',
        zipcode: '44122',
        city: 'Woodmere',
        street: 'Chagrin Boulevard',
        street_number: '28077',
        is_manual: true,
        is_temporary: false,
        building_type: null,
        state_name: 'OH',
        google_place_id: 'ChIJ85__BN0CMYgREuutObegMjk',
        is_valid: true,
        is_shippable: true,
        country: 'United States',
      },
      {
        id: 371302,
        firstname: 'Castlery 22',
        lastname: 'Wang',
        address1: '90024 Lewis and Clark Road',
        phone: '+1 (653) 333-3333',
        zipcode: '90024',
        city: 'Seaside',
        street: 'Lewis and Clark Road',
        street_number: '90024',
        is_manual: true,
        is_temporary: false,
        building_type: null,
        state_name: 'OR',
        google_place_id: 'ChIJBWzgLx9ik1QRaHRjelDGfXU',
        is_valid: true,
        is_shippable: false,
        country: 'United States',
      },
      {
        id: 371303,
        firstname: 'Castlery 22',
        lastname: 'Wang',
        address1: '20121 Hardwood Terrace',
        phone: '+1 (653) 533-3333',
        zipcode: '20147',
        city: 'Ashburn',
        street: 'Hardwood Terrace',
        street_number: '20121',
        is_manual: true,
        is_temporary: false,
        building_type: null,
        state_name: 'VA',
        google_place_id: 'ChIJpyqh_9s7tokRehoJagY3ibs',
        is_valid: true,
        is_shippable: true,
        country: 'United States',
      },
      {
        id: 371306,
        firstname: 'Abby',
        lastname: 'Wang',
        address1: '528  Felosa Drive',
        phone: '+1 (213) 944-5140',
        zipcode: '90036',
        city: 'Los Angeles',
        is_manual: true,
        is_temporary: false,
        building_type: null,
        state_name: 'CA',
        google_place_id: 'ChIJGSquI3y8woAR6Gd_SpR_pDY',
        is_valid: true,
        is_shippable: true,
        country: 'United States',
      },
    ],
    AddAddressSection: <PosAddAddress />,
  },
  render: (args) => {
    return <AddressList {...args} />;
  },
};
