FROM node:20-alpine AS base

WORKDIR /app

ENV NODE_ENV production
# Uncomment the following line in case you want to disable telemetry during runtime.
# ENV NEXT_TELEMETRY_DISABLED 1

# COPY --from=builder /app/public ./public

# Set the correct permission for prerender cache
RUN mkdir .next
# RUN chown nextjs:nodejs .next


# COPY /apps/pos/next.config.js .
# COPY /apps/pos/package.json .
# Automatically leverage output traces to reduce image size
# https://nextjs.org/docs/advanced-features/output-file-tracing
# COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
# COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static=

# issue: https://stackoverflow.com/questions/64947025/does-next-js-production-build-need-node-modules-folder-in-the-server
COPY ./.husky ./.husky
COPY  ./dist/apps/pos/.next/standalone ./
COPY  ./dist/apps/pos/.next/static ./dist/apps/pos/.next/static
COPY  ./dist/apps/pos/public ./dist/apps/pos

# 如果不存在node_modules
RUN \
  if [ ! -d "node_modules" ]; then \
    echo "node_modules not found, installing dependencies"; \
    npm install --omit=dev; \
  else \
    echo "node_modules found, skipping installation"; \
  fi

EXPOSE 3000

ENV PORT 3000
# set hostname to localhost
ENV HOSTNAME "0.0.0.0"

# server.js is created by next build from the standalone output
# https://nextjs.org/docs/pages/api-reference/next-config-js/output
CMD ["node", "apps/pos/server.js"]