backend:
  name: github
  repo: Lee-NG915/cBlog
  branch: main
  auth_type: pkce
  app_id: Ov23liAp6khZLw0XzQwN

site_url: https://lee-ng915.github.io/cBlog
display_url: https://lee-ng915.github.io/cBlog

media_folder: public/images/posts
public_folder: /images/posts

locale: zh_Hans

collections:
  - name: posts
    label: "博客文章"
    folder: "content/posts"
    path: "{{year}}/{{month}}/{{day}}/{{slug}}"
    create: true
    extension: md
    format: yaml-frontmatter
    slug: "{{slug}}"
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "发布日期", name: "date", widget: "datetime", format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false }
      - { label: "分类", name: "category", widget: "select", options: ["技术类", "日常生活", "学习记录", "旅游"], default: "技术类" }
      - { label: "摘要", name: "excerpt", widget: "text", required: false }
      - { label: "封面图片", name: "coverCard", widget: "image", required: false }
      - { label: "草稿", name: "draft", widget: "boolean", default: false, required: false }
      - { label: "正文", name: "body", widget: "markdown" }
