/* eslint-disable */
/**
 * Global Notice Fallback Data
 *
 * 这个文件由脚本自动生成，请勿手动编辑
 * 用于 getGlobalNotice 方法的 fallback 数据
 * 参考 apps/web/scripts/update-basic-container-resource-fallback.ts 的逻辑
 *
 * @generated
 * @lastUpdated 2025-12-10T10:03:10.200Z
 */

interface FallbackData {
  value: { noticeBarData: any[]; noticeBarMobileData: any[] };
  lastUpdated: string;
  note: string;
}

/**
 * 各市场的 Global Notice 兜底数据
 * 当 Storyblok API 不可用时使用这些数据
 *
 * Edge Runtime 兼容：数据在编译时打包进 bundle
 *
 * 数据结构对应 getGlobalNotice 方法的返回值
 */
export const FALLBACK_NOTICE_DATA: Record<string, FallbackData> = {
  sg: {
    value: {
      noticeBarData: [
        {
          _uid: '71515647-e1cb-4a97-857f-2f7f4726da20',
          link: '/sale/holiday-storewide-sale',
          intro: '',
          title: 'Holiday Sale: Enjoy upsized savings up to $600 off storewide.',
          pinned: false,
          ended_at: '2025-12-16 00:00',
          component: 'menu_block',
          image_url: '',
          permalink: '',
          action_text: '',
          region_code: [],
          published_at: '2025-12-08 00:00',
          background_color: '#420303',
          countdown_enabled: false,
          subscription_title: '',
          banner_background_image: '',
          countdown_background_gradient: '',
          banner_background_image_mobile: '',
        },
        {
          _uid: '2346dbd2-f99b-421a-a6cb-e07227ad9748',
          link: '/holiday-sale-event',
          intro: '',
          title: 'Holiday Event: Stand a chance to get your cart on us. RSVP now! >',
          pinned: false,
          ended_at: '2025-12-12 00:00',
          component: 'menu_block',
          image_url: '',
          permalink: '',
          action_text: '',
          region_code: [],
          published_at: '2025-12-05 00:00',
          background_color: '#420303',
          countdown_enabled: false,
          subscription_title: '',
          banner_background_image: '',
          countdown_background_gradient: '',
          banner_background_image_mobile: '',
        },
        {
          _uid: 'd11be993-bb36-4544-a9e1-f32f9ec827d6',
          link: '/new',
          intro: '',
          title: 'Discover new arrivals designed for outdoor living now.',
          pinned: false,
          ended_at: '2025-12-31 00:00',
          component: 'menu_block',
          image_url: '',
          permalink: '',
          action_text: '',
          region_code: [],
          published_at: '2025-08-07 12:00',
          background_color: '#420303',
          countdown_enabled: false,
          subscription_title: '',
          banner_background_image: '',
          countdown_background_gradient: '',
          banner_background_image_mobile: '',
        },
      ],
      noticeBarMobileData: [
        {
          _uid: 'e4d036b8-29cd-4f05-96fc-fd6dac6cd163',
          link: '/sale/holiday-storewide-sale',
          intro: '',
          title: 'Holiday Sale; Upsized: Save up to $600 off​',
          pinned: true,
          ended_at: '2025-12-16 00:00',
          component: 'menu_block',
          image_url: '',
          permalink: '',
          action_text: '',
          region_code: [],
          published_at: '2025-12-08 00:00',
          background_color: '#420303',
          countdown_enabled: true,
          subscription_title: '',
          banner_background_image: '',
          countdown_background_gradient: '',
          banner_background_image_mobile: '',
        },
        {
          _uid: '53d749ee-e762-4b8b-ac33-6eb0ee0b3933',
          link: '/holiday-sale-event',
          intro: '',
          title: 'RSVP for a chance to get your cart on us >',
          pinned: false,
          ended_at: '2025-12-12 00:00',
          component: 'menu_block',
          image_url: '',
          permalink: '',
          action_text: '',
          region_code: [],
          published_at: '2025-12-05 00:00',
          background_color: '#420303',
          countdown_enabled: false,
          subscription_title: '',
          banner_background_image: '',
          countdown_background_gradient: '',
          banner_background_image_mobile: '',
        },
        {
          _uid: '0a70be73-0588-4042-a81d-69f8511110d5',
          link: '/new',
          intro: '',
          title: 'New arrivals: Designed for living',
          pinned: false,
          ended_at: '2025-12-31 00:00',
          component: 'menu_block',
          image_url: '',
          permalink: '',
          action_text: '',
          region_code: [],
          published_at: '2025-08-07 12:00',
          background_color: '#420303',
          countdown_enabled: false,
          subscription_title: '',
          banner_background_image: '',
          countdown_background_gradient: '',
          banner_background_image_mobile: '',
        },
      ],
    },
    lastUpdated: '2025-12-10T10:03:07.320Z',
    note: 'Fallback data for SG notice. Updated: 12/10/2025, 6:03:07 PM',
  },
  us: {
    value: {
      noticeBarData: [
        {
          _uid: '2385c093-da7d-4bee-a77d-325349ced960',
          link: '/sale/holiday-sitewide-sale',
          intro: '',
          title: 'Holiday Sale: Take up to $400 off sitewide',
          pinned: false,
          ended_at: '2025-12-22 00:00',
          component: 'menu_block',
          image_url: '',
          permalink: '',
          action_text: '',
          region_code: [],
          published_at: '2025-12-08 00:00',
          background_color: '#424242',
          countdown_enabled: false,
          subscription_title: '',
          banner_background_image: '',
          countdown_background_gradient: '',
          banner_background_image_mobile: '',
        },
        {
          _uid: '0d2f4366-4861-41f0-848a-62b44a987fda',
          link: '/sale/living-add-on-bundle',
          intro: '',
          title: 'Living Room Add-on Bundle: Enjoy an extra 5% off living room furniture >',
          pinned: false,
          ended_at: '',
          component: 'menu_block',
          image_url: '',
          permalink: '',
          action_text: '',
          region_code: [],
          published_at: '2025-11-01 00:00',
          background_color: '#424242',
          countdown_enabled: false,
          subscription_title: '',
          banner_background_image: '',
          countdown_background_gradient: '',
          banner_background_image_mobile: '',
        },
      ],
      noticeBarMobileData: [
        {
          _uid: '86725f24-8782-4a23-88ac-bb71333878e5',
          link: '/sale/holiday-sitewide-sale',
          intro: '',
          title: 'Holiday Sale: Up to $400 off',
          pinned: false,
          ended_at: '2025-12-22 00:00',
          component: 'menu_block',
          image_url: '',
          permalink: '',
          action_text: '',
          region_code: [],
          published_at: '2025-12-08 00:00',
          background_color: '#424242',
          countdown_enabled: false,
          subscription_title: '',
          banner_background_image: '',
          countdown_background_gradient: '',
          banner_background_image_mobile: '',
        },
        {
          _uid: 'dbfffef3-91f3-49a1-b59e-c9f58a70a496',
          link: '/sale/living-add-on-bundle',
          intro: '',
          title: 'Living Add-on Bundle: Extra 5% off* >​',
          pinned: false,
          ended_at: '',
          component: 'menu_block',
          image_url: '',
          permalink: '',
          action_text: '',
          region_code: [],
          published_at: '2025-11-10 00:00',
          background_color: '#424242',
          countdown_enabled: false,
          subscription_title: '',
          banner_background_image: '',
          countdown_background_gradient: '',
          banner_background_image_mobile: '',
        },
      ],
    },
    lastUpdated: '2025-12-10T10:03:08.288Z',
    note: 'Fallback data for US notice. Updated: 12/10/2025, 6:03:08 PM',
  },
  au: {
    value: {
      noticeBarData: [
        {
          _uid: 'f3544c1d-40b9-4794-a081-01bc33e1df7c',
          link: 'sale/holiday-storewide-sale',
          intro: '',
          title: 'Take up to $400 off storewide + extra $150 off with code: HOLIDAY',
          pinned: true,
          ended_at: '2025-12-15 00:00',
          component: 'menu_block',
          image_url: '',
          permalink: '',
          action_text: '',
          region_code: [],
          published_at: '2025-12-08 00:00',
          background_color: '#424242',
          countdown_enabled: true,
          subscription_title: '',
          banner_background_image: '',
          countdown_background_gradient: '',
          banner_background_image_mobile: '',
        },
      ],
      noticeBarMobileData: [
        {
          _uid: '19a75aa9-a19c-4284-8d4f-93f8fc543489',
          link: 'sale/holiday-storewide-sale',
          intro: '',
          title: 'Up to $550 off storewide* ',
          pinned: true,
          ended_at: '2025-12-15 00:00',
          component: 'menu_block',
          image_url: '',
          permalink: '',
          action_text: '',
          region_code: [],
          published_at: '2025-12-08 00:00',
          background_color: '#424242',
          countdown_enabled: true,
          subscription_title: '',
          banner_background_image: '',
          countdown_background_gradient: '',
          banner_background_image_mobile: '',
        },
        {
          _uid: '0d21fed1-17d3-45e1-a7c2-8126039a7f19',
          link: 'new',
          intro: '',
          title: 'New arrivals: Designed for living',
          pinned: false,
          ended_at: '2026-05-01 16:40',
          component: 'menu_block',
          image_url: '',
          permalink: '',
          action_text: '',
          region_code: [],
          published_at: '2025-09-03 15:00',
          background_color: '#424242',
          countdown_enabled: false,
          subscription_title: '',
          banner_background_image: '',
          countdown_background_gradient: '',
          banner_background_image_mobile: '',
        },
      ],
    },
    lastUpdated: '2025-12-10T10:03:08.541Z',
    note: 'Fallback data for AU notice. Updated: 12/10/2025, 6:03:08 PM',
  },
  ca: {
    value: {
      noticeBarData: [
        {
          _uid: '7908a62e-10c2-4642-9602-0f54cea89b76',
          link: '/sale/boxing-day-sale',
          intro: '',
          title: 'Boxing Day Sale: Take up to $500 off sitewide',
          pinned: true,
          ended_at: '2025-12-22 00:00',
          component: 'menu_block',
          image_url: '',
          permalink: '',
          action_text: '',
          region_code: [],
          published_at: '2025-12-08 00:00',
          background_color: '#424242',
          countdown_enabled: false,
          subscription_title: '',
          banner_background_image: '',
          countdown_background_gradient: '',
          banner_background_image_mobile: '',
        },
        {
          _uid: 'ea84958c-e2db-4315-9b63-fbc0c2f31944',
          link: '/sale/living-add-on-bundle',
          intro: '',
          title: 'Living Room Add-on Bundle: Enjoy an extra 5% off living room furniture >',
          pinned: false,
          ended_at: '',
          component: 'menu_block',
          image_url: '',
          permalink: '',
          action_text: '',
          region_code: [],
          published_at: '',
          background_color: '#424242',
          countdown_enabled: false,
          subscription_title: '',
          banner_background_image: '',
          countdown_background_gradient: '',
          banner_background_image_mobile: '',
        },
        {
          _uid: '00b46951-e4de-4aaf-adf5-92d7e68d6990',
          link: '/new',
          intro: '',
          title: 'New arrivals: Designs worth coming home to',
          pinned: false,
          ended_at: '',
          component: 'menu_block',
          image_url: '',
          permalink: '',
          action_text: '',
          region_code: [],
          published_at: '2025-05-15 00:00',
          background_color: '#424242',
          countdown_enabled: false,
          subscription_title: '',
          banner_background_image: '',
          countdown_background_gradient: '',
          banner_background_image_mobile: '',
        },
      ],
      noticeBarMobileData: [
        {
          _uid: 'fb9f5f48-e429-4d90-bfa9-32ed28a891b2',
          link: '/sale/boxing-day-sale',
          intro: '',
          title: 'Boxing Day Sale: Up to  $500 off',
          pinned: true,
          ended_at: '2025-12-22 00:00',
          component: 'menu_block',
          image_url: '',
          permalink: '',
          action_text: '',
          region_code: [],
          published_at: '2025-12-08 00:00',
          background_color: '#424242',
          countdown_enabled: false,
          subscription_title: '',
          banner_background_image: '',
          countdown_background_gradient: '',
          banner_background_image_mobile: '',
        },
        {
          _uid: '6ba279b8-f14c-4a23-94e2-f7fc064b3ae8',
          link: '/sale/living-add-on-bundle',
          intro: '',
          title: 'Living Add-on Bundle: Extra 5% off* >',
          pinned: false,
          ended_at: '',
          component: 'menu_block',
          image_url: '',
          permalink: '',
          action_text: '',
          region_code: [],
          published_at: '',
          background_color: '#424242',
          countdown_enabled: false,
          subscription_title: '',
          banner_background_image: '',
          countdown_background_gradient: '',
          banner_background_image_mobile: '',
        },
        {
          _uid: '03610a0b-e51b-4baf-85d4-86b7feba3dcc',
          link: '/new',
          intro: '',
          title: 'New arrivals: Worth coming home to',
          pinned: false,
          ended_at: '',
          component: 'menu_block',
          image_url: '',
          permalink: '',
          action_text: '',
          region_code: [],
          published_at: '2025-05-15 00:00',
          background_color: '#424242',
          countdown_enabled: false,
          subscription_title: '',
          banner_background_image: '',
          countdown_background_gradient: '',
          banner_background_image_mobile: '',
        },
      ],
    },
    lastUpdated: '2025-12-10T10:03:09.583Z',
    note: 'Fallback data for CA notice. Updated: 12/10/2025, 6:03:09 PM',
  },
  uk: {
    value: {
      noticeBarData: [
        {
          _uid: '40c6f296-210e-4423-a95d-86248fd2f9d8',
          link: '/new',
          intro: '',
          title: 'New arrivals: Designed for living',
          pinned: true,
          ended_at: '2025-12-15 00:00',
          component: 'menu_block',
          image_url: '',
          permalink: '',
          action_text: '',
          region_code: [],
          published_at: '2025-12-08 00:00',
          background_color: '#424242',
          countdown_enabled: false,
          subscription_title: '',
          banner_background_image: '',
          countdown_background_gradient: '',
          banner_background_image_mobile: '',
        },
        {
          _uid: '8c1a5ed1-946d-4bd9-9f7e-b7c7d3260a81',
          link: '/new',
          intro: '',
          title: 'New arrivals: Designs worth coming home to',
          pinned: false,
          ended_at: '',
          component: 'menu_block',
          image_url: '',
          permalink: '',
          action_text: '',
          region_code: [],
          published_at: '2024-09-30 00:00',
          background_color: '#424242',
          countdown_enabled: false,
          subscription_title: '',
          banner_background_image: '',
          countdown_background_gradient: '',
          banner_background_image_mobile: '',
        },
      ],
      noticeBarMobileData: [
        {
          _uid: '003439cc-65e9-48e5-a393-c72acec57f8d',
          link: '/new',
          intro: '',
          title: 'New arrivals: Designed for living',
          pinned: true,
          ended_at: '2025-12-15 00:00',
          component: 'menu_block',
          image_url: '',
          permalink: '',
          action_text: '',
          region_code: [],
          published_at: '2025-12-08 00:00',
          background_color: '#424242',
          countdown_enabled: false,
          subscription_title: '',
          banner_background_image: '',
          countdown_background_gradient: '',
          banner_background_image_mobile: '',
        },
        {
          _uid: 'ac0eae8e-2ef8-4a9b-bff3-0f833bbd7a0e',
          link: '/new',
          intro: '',
          title: 'New arrivals: Worth coming home to',
          pinned: false,
          ended_at: '',
          component: 'menu_block',
          image_url: '',
          permalink: '',
          action_text: '',
          region_code: [],
          published_at: '2024-09-30 00:00',
          background_color: '#424242',
          countdown_enabled: false,
          subscription_title: '',
          banner_background_image: '',
          countdown_background_gradient: '',
          banner_background_image_mobile: '',
        },
      ],
    },
    lastUpdated: '2025-12-10T10:03:10.200Z',
    note: 'Fallback data for UK notice. Updated: 12/10/2025, 6:03:10 PM',
  },
};
