export const gtmPageNames = {
  homePage: 'home-page',
  categoryLandingPage: 'category-landing-page',
  categoryPage: 'category-page',
  salePage: 'sale-page',
  seoPage: 'seo-page',
  collectionPage: 'collection-page',
  productDetailPage: 'product-detail-page',
  accountPage: 'account-page',
  blogListPage: 'blogList-page',
  blogPage: 'blog-page',
  o2oPage: 'o2o-page',
  issPage: 'iss-page',
  searchPage: 'search-page',
  wishlistPage: 'wishlist-page',
  campaignPage: 'campaign-page',
  cartPage: 'cart-page',
  checkoutPage: 'checkout-page',
  reviewsPage: 'reviews-page',
  corporatePage: 'corporate-page',
  shopTheLookPage: 'shop-the-look-page',
  roomDesignerPage: 'room-designer-page',
};
export const gtmPageBasicParams = {
  'home-page': {
    pageCat: 'home',
    pageType: 'home',
    pageContent: 'home',
    pageProduct: 'home',
  },
  'category-landing-page': {
    pageCat: 'category-list',
    pageType: 'category-list',
    pageContent: 'category-list',
    pageProduct: 'other',
  },
  'category-page': {
    pageCat: 'product-list',
    pageType: 'product',
    pageContent: '',
    pageProduct: '',
  },
  'sale-page': {
    pageCat: 'product-list',
    pageType: 'product',
    pageContent: 'promotion',
    pageProduct: '',
  },
  'seo-page': {
    pageCat: 'product-list',
    pageType: 'product',
    pageContent: 'seo',
    pageProduct: '',
  },
  'collection-page': {
    pageCat: 'product-list',
    pageType: 'product',
    pageContent: 'collection',
    pageProduct: '',
  },
  'product-detail-page': {
    pageCat: 'product-detail',
    pageType: 'product',
    pageContent: '',
    pageProduct: '',
  },
  'account-page': {
    pageCat: 'account',
    pageType: 'account',
    pageContent: 'account',
    pageProduct: 'other',
  },
  'blogList-page': {
    pageCat: 'blog',
    pageType: 'blog',
    pageContent: 'blog',
    pageProduct: 'other',
  },
  'blog-page': {
    pageCat: 'blog',
    pageType: 'blog',
    pageContent: 'blog',
    pageProduct: 'other',
  },
  'o2o-page': {
    pageCat: 'o2o',
    pageType: 'o2o',
    pageContent: 'o2o',
    pageProduct: 'other',
  },
  'iss-page': {
    pageCat: 'iss',
    pageType: 'iss',
    pageContent: 'iss',
    pageProduct: 'other',
  },
  'search-page': {
    pageCat: 'search',
    pageType: 'search',
    pageContent: 'search',
    pageProduct: 'other',
  },
  'wishlist-page': {
    pageCat: 'account',
    pageType: 'account',
    pageContent: 'account',
    pageProduct: 'other',
  },
  'campaign-page': {
    pageCat: 'campaign',
    pageType: 'campaign',
    pageContent: 'promotion',
    pageProduct: 'other',
  },
  'cart-page': {
    pageCat: 'cart',
    pageType: 'cart',
    pageContent: 'cart',
    pageProduct: 'other',
  },
  'checkout-page': {
    pageCat: '',
    pageType: '',
    pageContent: '',
    pageProduct: 'other',
  },
  'reviews-page': {
    pageCat: 'reviews',
    pageType: 'reviews',
    pageContent: 'reviews',
    pageProduct: 'other',
  },
  'corporate-page': {
    pageCat: 'corporate',
    pageType: 'corporate',
    pageContent: 'corporate',
    pageProduct: 'other',
  },
  'shop-the-look-page': {
    pageType: 'shop-the-look',
    pageCat: 'Not Found',
    pageContent: 'Not Found',
    pageProduct: 'Not Found',
  },
  'room-designer-page': {
    pageType: 'room-designer',
    pageCat: 'Not Found',
    pageContent: 'Not Found',
    pageProduct: 'Not Found',
  },
};
