// Platform bindings are generated by `pnpm --filter @cblog/knowledge-api types`.
export type Bindings = {
  [K in keyof Env]: Env[K] extends string ? string : Env[K];
} & { GITHUB_CLIENT_SECRET?: string; BUILD_DISPATCH_TOKEN?: string; BUILD_PIPELINE_SECRET?: string };
export type Note = {
  id: string;
  slug: string;
  title: string;
  body: string;
  topic_id: string | null;
  state: "draft" | "ready" | "archived";
  visibility: "owner" | "public";
  tags: string;
  version: number;
  updated_at: string;
  deleted_at: string | null;
  source_path: string | null;
};
export type Group = {
  id: string;
  name: string;
  kind: "domain" | "topic" | "path" | "project";
  parent_id: string | null;
  position: number;
  version: number;
};
