import { isOutdated, isBefore } from 'utils/time';
import { showLoyalTyV2Requirements } from 'utils/loyaltyV2';
import { enableGuarantee } from 'config';

export default [
  {
    key: 'home',
    url: '/',
    disabledCountries: [],
    notIndexedCountries: [],
  },
  {
    key: 'login',
    url: '/login',
    disabledCountries: [],
    notIndexedCountries: ['US', 'AU', 'UK', 'SG', 'CA'],
  },
  {
    key: 'signup',
    url: '/signup',
    disabledCountries: [],
    notIndexedCountries: ['US', 'AU', 'UK', 'SG', 'CA'],
  },
  {
    key: 'forgot-password',
    url: '/forgot-password',
    disabledCountries: [],
    notIndexedCountries: ['US', 'AU', 'UK', 'SG', 'CA'],
  },
  {
    key: 'unsubscribe',
    url: '/unsubscribe',
    disabledCountries: [],
    notIndexedCountries: ['US', 'AU', 'UK', 'SG', 'CA'],
  },
  {
    key: 'wishlist',
    url: '/wishlist',
    disabledCountries: [],
    notIndexedCountries: ['US', 'AU', 'UK', 'SG', 'CA'],
  },
  {
    key: 'wishlist-products',
    url: '/wishlist/products',
    disabledCountries: [],
    notIndexedCountries: ['US', 'AU', 'UK', 'SG', 'CA'],
  },
  {
    key: 'wishlist-looks',
    url: '/wishlist/looks',
    disabledCountries: [],
    notIndexedCountries: ['US', 'AU', 'UK', 'SG', 'CA'],
  },
  {
    key: 'shop-the-look',
    url: '/shop-the-look',
    disabledCountries: [],
    notIndexedCountries: ['US', 'AU', 'UK', 'SG', 'CA'],
  },
  {
    key: 'stl-living-room',
    url: '/shop-the-look/living-room',
    disabledCountries: [],
    notIndexedCountries: [],
  },
  {
    key: 'stl-dining-room',
    url: '/shop-the-look/dining-room',
    disabledCountries: [],
    notIndexedCountries: [],
  },
  {
    key: 'stl-bedroom',
    url: '/shop-the-look/bedroom',
    disabledCountries: [],
    notIndexedCountries: [],
  },
  {
    key: 'stl-outdoor',
    url: '/shop-the-look/outdoor',
    disabledCountries: [],
    notIndexedCountries: [],
  },
  {
    key: 'stl-by-collection',
    url: '/shop-the-look/by-collection',
    disabledCountries: [],
    notIndexedCountries: [],
  },
  {
    key: 'virtual-studio',
    url: '/virtual-studio',
    disabledCountries: ['SG', 'US', 'AU', 'CA', 'UK'],
    notIndexedCountries: ['US', 'AU', 'CA', 'UK'],
  },
  {
    key: 'stay-home',
    url: '/stay-home',
    disabledCountries: [],
    notIndexedCountries: ['US', 'SG', 'AU', 'UK', 'CA'],
  },
  {
    key: 'blog',
    url: '/blog',
    disabledCountries: [],
    notIndexedCountries: [],
  },
  {
    key: 'furniture-configurator-tool',
    url: '/furniture-configurator-tool',
    disabledCountries: [],
    notIndexedCountries: [],
  },
  {
    key: 'o2o',
    url: '/showroom-exclusives',
    disabledCountries: ['US', 'AU', 'UK', 'CA'],
    notIndexedCountries: [],
  },
  {
    key: 'interior-styling-service',
    url: '/interior-styling-service',
    disabledCountries: ['US', 'AU', 'UK', 'CA'],
    notIndexedCountries: [],
  },
  {
    key: 'profile',
    url: '/account/profile',
    disabledCountries: [],
    notIndexedCountries: ['US', 'AU', 'UK', 'SG', 'CA'],
  },
  {
    key: 'orders',
    url: '/account/orders',
    disabledCountries: [],
    notIndexedCountries: ['US', 'AU', 'UK', 'SG', 'CA'],
  },
  {
    key: 'vouchers',
    url: '/account/vouchers',
    disabledCountries: [],
    notIndexedCountries: ['US', 'AU', 'UK', 'SG', 'CA'],
  },
  {
    key: 'address',
    url: '/account/address',
    disabledCountries: [],
    notIndexedCountries: ['US', 'AU', 'UK', 'SG', 'CA'],
  },
  {
    key: 'order-details',
    url: '/account/order-details',
    disabledCountries: [],
    notIndexedCountries: ['US', 'AU', 'UK', 'SG', 'CA'],
  },
  {
    key: 'submit-review',
    url: '/submit-review',
    disabledCountries: [],
    notIndexedCountries: ['US', 'AU', 'UK', 'SG', 'CA'],
  },
  {
    key: 'my-reviews',
    url: '/account/reviews',
    disabledCountries: [],
    notIndexedCountries: ['US', 'AU', 'UK', 'SG', 'CA'],
  },
  {
    key: 'cart',
    url: '/cart',
    disabledCountries: [],
    notIndexedCountries: ['US', 'AU', 'UK', 'SG', 'CA'],
  },
  {
    key: 'checkout-account',
    url: '/checkout/account',
    disabledCountries: [],
    notIndexedCountries: ['US', 'AU', 'UK', 'SG', 'CA'],
  },
  {
    key: 'checkout-shipping-address',
    url: '/checkout/shipping-address',
    disabledCountries: [],
    notIndexedCountries: ['US', 'AU', 'UK', 'SG', 'CA'],
  },
  {
    key: 'checkout-shipping-method',
    url: '/checkout/shipping-method',
    disabledCountries: [],
    notIndexedCountries: ['US', 'AU', 'UK', 'SG', 'CA'],
  },
  {
    key: 'checkout-payment',
    url: '/checkout/payment',
    disabledCountries: [],
    notIndexedCountries: ['US', 'AU', 'UK', 'SG', 'CA'],
  },
  {
    key: 'checkout-2c2p',
    url: '/checkout/tctp-payment',
    disabledCountries: [],
    notIndexedCountries: ['US', 'AU', 'UK', 'SG', 'CA'],
  },
  {
    key: 'checkout-grabpay',
    url: '/checkout/grabpay',
    disabledCountries: ['US', 'AU', 'UK', 'CA'],
    notIndexedCountries: ['SG'],
  },
  {
    key: 'checkout-success',
    url: '/checkout/success',
    disabledCountries: [],
    notIndexedCountries: ['US', 'AU', 'UK', 'SG', 'CA'],
  },
  {
    key: 'checkout-empty',
    url: '/checkout/empty-cart',
    disabledCountries: [],
    notIndexedCountries: ['US', 'AU', 'UK', 'SG', 'CA'],
  },
  {
    key: 'contact-us',
    url: '/contact-us',
    disabledCountries: [],
    notIndexedCountries: [],
  },
  {
    key: 'our-story',
    url: '/our-story',
    disabledCountries: [],
    notIndexedCountries: [],
  },
  {
    key: 'manufacturing-quality',
    url: '/manufacturing-quality',
    disabledCountries: ['US', 'CA'],
    notIndexedCountries: [],
  },
  {
    key: 'studio',
    url: '/studio',
    image:
      'https://res.cloudinary.com/castlery/image/upload/w_1080,f_auto,q_auto/v1529074421/static/launch/jitpoh2.jpg',
    disabledCountries: ['US', 'SG', 'CA'],
    notIndexedCountries: [],
  },
  {
    key: 'showroom',
    url: '/showroom',
    image:
      'https://res.cloudinary.com/castlery/image/upload/w_1080,f_auto,q_auto/v1529074421/static/launch/jitpoh2.jpg',
    disabledCountries: ['US', 'CA'],
    notIndexedCountries: [],
  },
  {
    key: 'sydney-showroom',
    url: '/sydney-showroom',
    disabledCountries: ['US', 'SG', 'CA', 'UK'],
    notIndexedCountries: [],
  },
  {
    key: 'swatches',
    url: '/swatches',
    disabledCountries: [],
    notIndexedCountries: [],
  },
  {
    key: 'zip',
    url: '/zip',
    disabledCountries: ['US', 'SG', 'CA'],
    notIndexedCountries: ['AU', 'UK'],
  },
  {
    key: 'trade',
    url: '/trade',
    disabledCountries: [],
    notIndexedCountries: [],
  },
  {
    key: 'affiliate-program',
    url: '/affiliate-program',
    disabledCountries: [],
    notIndexedCountries: [],
  },
  {
    key: 'delivery',
    url: '/delivery',
    disabledCountries: [],
    notIndexedCountries: [],
  },
  {
    key: 'accessibility',
    url: '/accessibility',
    disabledCountries: ['AU', 'SG'],
    notIndexedCountries: [],
  },
  {
    key: 'referral-terms',
    url: '/referral-terms',
    disabledCountries: [],
    notIndexedCountries: ['SG', 'US', 'AU', 'UK', 'CA'],
  },
  {
    key: 'referral-issue',
    url: '/referral-issue',
    disabledCountries: [],
    notIndexedCountries: ['US', 'AU', 'UK', 'SG', 'CA'],
  },
  {
    key: 'press',
    url: '/press',
    disabledCountries: [],
    notIndexedCountries: [],
  },
  {
    key: 'terms-of-use',
    url: '/terms-of-use',
    disabledCountries: [],
    notIndexedCountries: [],
  },
  {
    key: 'sales-and-refunds',
    url: '/sales-and-refunds',
    disabledCountries: [],
    notIndexedCountries: [],
  },
  {
    key: 'store-credits-terms',
    url: showLoyalTyV2Requirements ? '/the-castlery-club-terms' : '/store-credits-terms',
    disabledCountries: [],
    notIndexedCountries: [],
  },
  {
    key: 'warranty',
    url: enableGuarantee ? '/guarantee' : '/warranty',
    disabledCountries: [],
    notIndexedCountries: [],
  },
  {
    key: 'promo-terms',
    url: '/promo-terms',
    disabledCountries: [],
    notIndexedCountries: [],
  },
  {
    key: 'privacy-policy',
    url: '/privacy-policy',
    disabledCountries: [],
    notIndexedCountries: [],
  },
  {
    key: 'help-center',
    url: '/help-center',
    disabledCountries: [],
    notIndexedCountries: [],
  },
  {
    key: 'reset-password',
    url: '/reset-password',
    disabledCountries: [],
    notIndexedCountries: ['US', 'AU', 'UK', 'SG', 'CA'],
  },
  {
    key: 'reviews',
    url: '/reviews',
    disabledCountries: [],
    notIndexedCountries: [],
  },
  {
    key: 'at-home-with-castlery',
    url: '/at-home-with-castlery',
    disabledCountries: [],
    notIndexedCountries: ['US', 'AU', 'UK', 'SG', 'CA'],
  },
  {
    key: 'accident-protection-plan-faq',
    url: '/accident-protection-plan-faq',
    disabledCountries: ['US', 'SG', 'CA'],
    notIndexedCountries: ['AU', 'UK'],
  },
  {
    key: 'style-contest',
    url: '/styling-contest',
    disabledCountries: ['US', 'AU', 'UK', 'SG', 'CA'],
    notIndexedCountries: [],
  },
  {
    key: 'schedule-delivery',
    url: '/schedule-delivery',
    disabledCountries: ['US', 'AU', 'UK', 'CA'],
    notIndexedCountries: ['SG'],
  },
  {
    key: 'delivery-review',
    url: '/delivery-review',
    disabledCountries: [],
    notIndexedCountries: ['US', 'AU', 'UK', 'SG', 'CA'],
  },
  {
    key: 'feat',
    url: '/feat',
    disabledCountries: [],
    notIndexedCountries: ['US', 'AU', 'UK', 'SG', 'CA'],
  },
  {
    key: 'interior-design',
    url: '/interior-design',
    disabledCountries: ['US', 'AU', 'UK', 'SG', 'CA'],
    notIndexedCountries: [],
  },
  {
    key: 'designers',
    url: '/designers',
    disabledCountries: [],
    notIndexedCountries: ['US', 'AU', 'UK', 'SG', 'CA'],
  },
  {
    key: 'designer-community',
    url: '/designer-community',
    disabledCountries: ['CA', 'UK'],
    notIndexedCountries: ['CA', 'UK'],
  },
  {
    key: 'birthday-sale',
    url: '/birthday-sale',
    disabledCountries: ['US', 'AU', 'UK', 'SG', 'CA'],
    notIndexedCountries: [],
  },
  {
    key: 'warehouse-sale',
    url: '/warehouse-sale',
    disabledCountries: ['US', 'AU', 'UK', 'SG', 'CA'],
    notIndexedCountries: [],
  },
  {
    key: 'warehouse-sale-tutorial',
    url: '/warehouse-sale-tutorial',
    disabledCountries: ['US', 'AU', 'UK', 'SG', 'CA'],
    notIndexedCountries: [],
  },
  {
    key: 'rsvp',
    url: '/rsvp',
    disabledCountries: ['US', 'AU', 'UK', 'CA'],
    notIndexedCountries: ['SG'],
  },
  {
    key: 'christmas',
    url: '/christmas',
    disabledCountries: ['US', 'AU', 'UK', 'CA'],
    notIndexedCountries: ['SG'],
  },
  {
    key: 'new-year',
    url: '/new-year',
    disabledCountries: [],
    notIndexedCountries: ['US', 'AU', 'UK', 'SG', 'CA'],
  },
  {
    key: 'lunar-new-year',
    url: '/lunar-new-year',
    disabledCountries: ['US', 'AU', 'UK', 'SG', 'CA'],
    notIndexedCountries: [],
  },
  {
    key: 'lunar-new-year-event',
    url: '/lunar-new-year-event',
    disabledCountries: ['US', 'AU', 'UK', 'CA'],
    notIndexedCountries: ['SG'],
    publishedAt: '2023-01-09 00:00',
    endedAt: '2023-01-15 23:59',
    effective: !isOutdated('2023-01-09 00:00', '2023-01-15 23:59'),
    isPromoteTime: !isOutdated('2023-01-09 00:00', '2023-01-13 23:59'),
    isActualTime: !isOutdated('2023-01-14 00:00', '2023-01-15 23:59'),
  },
  {
    key: 'mid-year-sale',
    url: {
      SG: '/midyear-sale',
      US: '/midyear-sale',
      CA: '/midyear-sale',
      AU: '/eofy-sale',
      UK: '/eofy-sale',
    },
    disabledCountries: [],
    notIndexedCountries: ['US', 'AU', 'UK', 'SG', 'CA'],
  },
  {
    key: 'new-way-of-living',
    url: '/new-way-of-living',
    disabledCountries: [],
    notIndexedCountries: ['US', 'AU', 'UK', 'SG', 'CA'],
  },
  {
    key: 'furniture-sydney',
    url: '/furniture-sydney',
    disabledCountries: ['US', 'SG', 'CA'],
    notIndexedCountries: ['AU', 'UK'],
  },
  {
    key: 'furniture-melbourne',
    url: '/furniture-melbourne',
    disabledCountries: ['US', 'SG', 'CA'],
    notIndexedCountries: ['AU', 'UK'],
  },
  {
    key: 'new-homeowners',
    url: '/new-homeowners',
    disabledCountries: ['US', 'AU', 'UK', 'CA'],
    notIndexedCountries: [],
  },
  {
    key: 'celebrate-home-giveaway',
    url: '/celebrate-home-giveaway',
    disabledCountries: ['US', 'AU', 'UK', 'SG', 'CA'],
    notIndexedCountries: [],
  },
  {
    key: 'product',
    url: '/products',
    disabledCountries: [],
    notIndexedCountries: ['US', 'AU', 'UK', 'SG', 'CA'],
  },
  {
    key: 'pla',
    url: '/pla',
    disabledCountries: [],
    notIndexedCountries: ['US', 'AU', 'UK', 'SG', 'CA'],
  },
  {
    key: 'search',
    url: '/search',
    image: 'https://res.cloudinary.com/castlery/image/upload/v1648713427/knight/category/banner/search.jpg',
    imageResponsive:
      'https://res.cloudinary.com/castlery/image/upload/v1648713427/knight/category/banner/search-mobile.jpg',
    disabledCountries: [],
    notIndexedCountries: ['US', 'AU', 'UK', 'SG', 'CA'],
  },
  {
    key: 'as-is',
    url: '/as-is',
    permalink: 'as-is',
    image:
      'https://res.cloudinary.com/castlery/image/upload/v1536655591/marketing/SG/category/salebanner_UpholsterySale_Desktop.jpg',
    imageResponsive:
      'https://res.cloudinary.com/castlery/image/upload/v1536655597/marketing/SG/category/Salebanner_UpholsterySale_Mobile.jpg',
    disabledCountries: ['US', 'AU', 'UK', 'SG', 'CA'],
    notIndexedCountries: [],
  },
  {
    key: 'asis-beds',
    url: '/as-is/beds',
    permalink: 'asis-beds',
    image:
      'https://res.cloudinary.com/castlery/image/upload/v1536655591/marketing/SG/category/salebanner_UpholsterySale_Desktop.jpg',
    imageResponsive:
      'https://res.cloudinary.com/castlery/image/upload/v1536655597/marketing/SG/category/Salebanner_UpholsterySale_Mobile.jpg',
    disabledCountries: ['US', 'AU', 'UK', 'SG', 'CA'],
    notIndexedCountries: [],
  },
  {
    key: 'collections',
    url: '/collections',
    disabledCountries: ['US', 'AU', 'UK', 'SG', 'CA'],
    notIndexedCountries: [],
  },
  {
    key: 'living-room',
    permalink: 'living-room',
    socialCollection: 'living',
    disabledCountries: ['US', 'AU', 'UK', 'SG', 'CA'],
    notIndexedCountries: [],
  },
  {
    key: 'dining-room',
    permalink: 'dining-room',
    socialCollection: 'dining',
    disabledCountries: ['US', 'AU', 'UK', 'SG', 'CA'],
    notIndexedCountries: [],
  },
  {
    key: 'bedroom',
    permalink: 'bedroom',
    socialCollection: 'bedroom',
    disabledCountries: ['US', 'AU', 'UK', 'SG', 'CA'],
    notIndexedCountries: [],
  },
  {
    key: 'home-office',
    permalink: 'home-office',
    socialCollection: 'storage',
    disabledCountries: ['US', 'AU', 'UK', 'SG', 'CA'],
    notIndexedCountries: [],
  },
  {
    key: 'storage',
    permalink: 'storage',
    socialCollection: 'storage',
    disabledCountries: ['US', 'AU', 'UK', 'SG', 'CA'],
    notIndexedCountries: [],
  },
  {
    key: 'furniture-sets',
    permalink: 'furniture-sets',
    disabledCountries: [],
    notIndexedCountries: [],
  },
  {
    key: 'lighting',
    permalink: 'lighting',
    disabledCountries: ['US', 'AU', 'UK', 'SG', 'CA'],
    notIndexedCountries: [],
  },
  {
    key: 'accessories',
    permalink: 'accessories',
    socialCollection: 'other',
    disabledCountries: ['US', 'AU', 'UK', 'SG', 'CA'],
    notIndexedCountries: [],
  },
  {
    key: 'rugs',
    disabledCountries: ['US', 'AU', 'UK', 'SG', 'CA'],
    notIndexedCountries: [],
  },
  {
    key: 'poufs-cushion-pillows',
    permalink: 'poufs-cushions-throws',
    disabledCountries: ['US', 'AU', 'UK', 'SG', 'CA'],
    notIndexedCountries: [],
  },
  {
    key: 'fabric-care',
    disabledCountries: [],
    notIndexedCountries: [],
  },
  {
    key: 'entryway',
    permalink: 'entryway',
    socialCollection: 'storage',
    disabledCountries: ['US', 'AU', 'UK', 'SG', 'CA'],
    notIndexedCountries: [],
  },
  {
    key: 'bedding',
    permalink: 'bedding',
    disabledCountries: ['US', 'AU', 'UK', 'SG', 'CA'],
    notIndexedCountries: [],
  },
  {
    key: 'tableware',
    permalink: 'tableware',
    disabledCountries: ['US', 'AU', 'UK', 'SG', 'CA'],
    notIndexedCountries: [],
  },
  {
    key: 'mirrors-wall-art',
    disabledCountries: ['US', 'AU', 'UK', 'SG', 'CA'],
    notIndexedCountries: [],
  },
  {
    key: 'organisation',
    disabledCountries: ['US', 'AU', 'UK', 'SG', 'CA'],
    notIndexedCountries: [],
  },
  {
    key: 'outdoor',
    permalink: 'outdoor',
    socialCollection: 'outdoor',
    disabledCountries: [],
    notIndexedCountries: [],
  },
  {
    key: 'referral',
    url: '/referral',
    disabledCountries: [],
    notIndexedCountries: [],
  },
  {
    key: 'rewards', // 有getUrl指向这里，所以不要改key
    url: showLoyalTyV2Requirements ? '/the-castlery-club' : '/rewards',
    disabledCountries: [],
    notIndexedCountries: [],
  },
  {
    key: 'account-rewards',
    url: showLoyalTyV2Requirements ? '/account/the-castlery-club' : '/account/rewards',
    disabledCountries: [],
    notIndexedCountries: ['US', 'AU', 'UK', 'SG', 'CA'],
  },
  {
    key: 'mindscape',
    url: '/mindscape',
    disabledCountries: ['US', 'SG', 'CA'],
    notIndexedCountries: ['AU', 'UK'],
  },
  {
    key: 'rich',
    url: '/rich',
    disabledCountries: ['US', 'SG', 'CA'],
    notIndexedCountries: ['AU', 'UK'],
  },
  {
    key: 'wondery',
    url: '/wondery',
    disabledCountries: ['US', 'SG', 'CA'],
    notIndexedCountries: ['AU', 'UK'],
  },
  {
    key: 'thedollop',
    url: '/thedollop',
    disabledCountries: ['AU', 'UK', 'SG'],
    notIndexedCountries: ['US', 'CA'],
  },
  {
    key: 'eventherich',
    url: '/eventherich',
    disabledCountries: ['AU', 'UK', 'SG'],
    notIndexedCountries: ['US', 'CA'],
  },
  {
    key: 'sitemap',
    url: '/sitemap',
    disabledCountries: [],
    notIndexedCountries: [],
  },
  {
    key: 'livetrue',
    url: '/livetrue',
    disabledCountries: ['AU', 'UK', 'US', 'CA'],
    notIndexedCountries: [],
    effective: isBefore('2023-07-10 00:00'),
  },
  {
    key: 'room-designer',
    url: '/room-designer',
    disabledCountries: [],
    notIndexedCountries: [],
  },
];
