/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: 998f522ca82ba776a91bd429776a735c)
interface __BaseEnv_Env {
	IMAGES: KVNamespace;
	DB: D1Database;
	ASSETS: Fetcher;
	APP_ENV: string;
	OWNER_GITHUB_ID: string;
	GITHUB_CLIENT_ID: string;
	PUBLIC_ORIGIN: string;
	AI_ENABLED: string;
	BUILD_PIPELINE_ENABLED: string;
	BUILD_REPOSITORY: string;
	BUILD_REF: string;
	BUILD_WORKFLOW: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ENV" | "OWNER_GITHUB_ID" | "GITHUB_CLIENT_ID" | "PUBLIC_ORIGIN" | "AI_ENABLED" | "BUILD_PIPELINE_ENABLED" | "BUILD_REPOSITORY" | "BUILD_REF" | "BUILD_WORKFLOW">> {}
}
